services:
  - type: web
    name: ecomm-pago-product
    plan: free
    branch: main
    rootDir: ./product
    dockerCommand: ./product/Dockerfile
  - type: web
    name: ecomm-pago-account
    plan: free
    branch: main
    rootDir: ./account
    dockerCommand: ./account/Dockerfile
  - type: web
    name: ecomm-pago-order
    plan: free
    branch: main
    rootDir: ./order
    dockerCommand: ./order/Dockerfile
  - type: web
    name: ecomm-pago-finance
    plan: free
    branch: main
    rootDir: ./finance
    dockerCommand: ./finance/Dockerfile
