name: Ecommerce PagoShop Build
on: ['push', 'pull_request']
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building Ecommerce PagoShop Enviroment
        run: docker-compose up -d --build

