name: Ecommerce PagoShop Tests
on: ['push', 'pull_request']
jobs:
  check-lint:
    name: Checking lint errors
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: npx eslint
        name: Searching for errors
  test-products:
    name: Testing Products Services
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: npm test
        working-directory: product
        name: Testing Products