name: Ecommerce PagoShop Tests
on: ['push', 'pull_request']
jobs:
  tests-pagoshop:
    name: Running all tests for Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building Ecommerce PagoShop Enviroment
        run: docker-compose up -d --build
      - name: Testing Products
        run: docker ps -a
        run: docker ps -a
        run: docker ps -a
    