name: Ecommerce PagoShop Tests
on: ['push', 'pull_request']
jobs:
  tests-pagoshop:
    name: Running all tests for Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing Dependencies
        working-directory: product
        run: npm install
      # - name: Testing Products
      #   run: docker ps -a
      # - name: Testing Products
      #   run: docker ps -a
      # - name: Testing Products
      #   run: docker exec product-ecomm npm test
    