name: Ecommerce PagoShop Tests
on: ['push', 'pull_request']
jobs:
  tests-pagoshop:
    name: Running all tests for Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing Dependencies On Products
        working-directory: product
        run: npm install
      - name: Installing Dependencies On Accounts
        working-directory: account
        run: npm install
      - name: Installing Dependencies On Order
        working-directory: order
        run: npm install
      - name: Installing Dependencies On Finance
        working-directory: finance
        run: npm install
      # - name: Testing Products
      #   run: docker ps -a
      # - name: Testing Products
      #   run: docker ps -a
      # - name: Testing Products
      #   run: docker exec product-ecomm npm test
    